---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: azure-voting
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: GitOps
  secretRef:
    name: azure-voting
  url: https://github.com/duffney/secure-supply-chain-on-aks/
