on:
  push:
    branches:
        - copaGitOps

jobs:
    patch:
        runs-on: ubuntu-latest

        strategy:
          fail-fast: false
          matrix:
                # provide relevant list of images to scan on each run
                images: ['s3cexampleacr.azurecr.io/azure-voting-app-rust:v0.1.0-alpha'] # add more for microservices TODO later

        steps:
        - name: Login to Azure
          id: login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      
        - name: Login to Azure Container Registry
          run: |
              az acr login --name ${{ vars.ACR_NAME }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@dedd61cf5d839122591f5027c89bf3ad27691d18

        - name: Generate Trivy Report
          uses: aquasecurity/trivy-action@69cbbc0cbbf6a2b0bab8dcf0e9f2d7ead08e87e4
          with:
            scan-type: 'image'
            format: 'json'
            output: 'report.json'
            ignore-unfixed: true
            vuln-type: 'os'
            image-ref: ${{ matrix.images }}

        - name: Check Vuln Count
          id: vuln_count
          run: |
            report_file="report.json"
            vuln_count=$(jq '.Results | length' "$report_file")
            echo "vuln_count=$vuln_count" >> $GITHUB_OUTPUT

        - name: Extract Patched Tag 
          id: extract_tag
          run: |
            current_tag=$(echo ${{ matrix.images }} | cut -d ':' -f2)
            
            if [[ $current_tag == *-* ]]; then
                numeric_tag=$(echo "$current_tag" | awk -F'-' '{print $NF}')
                non_numeric_tag=$(echo "$current_tag" | sed "s#-$numeric_tag##g")
                incremented_tag=$((numeric_tag+1))
                new_tag="$non_numeric_tag-$incremented_tag"
            else
                new_tag="$current_tag-1"
            fi
            
            echo "::set-output name=patched_tag::$new_tag"
            echo "patched_tagNew=$new_tag" >> $GITHUB_OUTPUT


        - name: debug
          run: |
            echo "patched_tag=$patched_tag"
            echo "patched_tagNew=$patched_tagNew"

        - name: Copa Action
          if: steps.vuln_count.outputs.vuln_count != '0'
          id: copa
          uses: project-copacetic/copa-action@v1.0.0
          with:
            image: ${{ matrix.images }}
            image-report: 'report.json'
            patched-tag: ${{ steps.extract_tag.outputs.patched_tag }}
            buildkit-version: 'v0.11.6'
            # optional, default is latest
            copa-version: '0.3.0'

        - name: Docker Push Patched Image
          if: steps.login.conclusion == 'success'
          run: |
            docker push ${{ steps.copa.outputs.patched-image }}
